apiVersion: v1
kind: Service
metadata:
  name: rds-service
spec:
  type: ExternalName
  externalName: jdbc:mysql://database-1.c5gs8ey0ghui.us-east-1.rds.amazonaws.com:3306/spring
  ports:
    - protocol: TCP
      port: 3306