#services:
#  server:
#    image: spring-image:latest
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/employeedb
#      - SPRING_DATASOURCE_USERNAME=sa
#      - SPRING_DATASOURCE_PASSWORD=1234
##    environment:
##      - spring.datasource.url=jdbc:mysql://mysqldb:3306/employeedb  #?useSSL=false
#    networks:
#      - springmysql-net
#
#    depends_on:
#      - mysqldb
#
#  mysqldb:
#    image: mysql:8.0.36
#    ports:
#      - 3307:3306
#    networks:
#      - springmysql-net
#    environment:
#      - MYSQL_ROOT_PASSWORD=1234
#      - MYSQL_DATABASE=employeedb
#      - MYSQL_USER=sa
#      - MYSQL_PASSWORD=1234
#
#networks:
#  springmysql-net:
#
#---


#---
#version: "3.7"
#services:
#  api_service:
#    build: .
#    restart: always
#    ports:
#      - 8998:8998
#    networks:
#      - springapimysql-net
#    environment:
#      - spring.datasource.url=jdbc:mysql://mysqldb:3306/k8s?allowPublicKeyRetrieval=true
#    depends_on:
#      - mysqldb
#
#    volumes:
#      - .m2:/root/.m2
#
#  mysqldb:
#    image: "mysql:8.0.36"
#    restart: always
#    ports:
#      - 3307:3307
#    networks:
#      - springapimysql-net
#    environment:
#      MYSQL_DATABASE: k8s
#      MYSQL_USER: root
#      MYSQL_PASSWORD: raju
#      MYSQL_ROOT_PASSWORD: raju
#networks:
#  springapimysql-net:
#
#---

version: '3.8' # Specify the Compose file version
services:
  db:
    image: mysql:8.0.36   # MySQL image
    container_name: mysql-db # Optional: Set container name for MySQL
    environment:
      MYSQL_DATABASE: k8s
      MYSQL_USER: root
      MYSQL_PASSWORD: raju
      MYSQL_ROOT_PASSWORD: raju
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql  # Persist data in a Docker volume
    networks:
      - springboot-mysql-net

  app:
    image: your-spring-boot-app-image # Replace with your Spring Boot image name
    container_name: spring-app
    build:
      context: .                      # Path to your Dockerfile
    ports:
      - "8998:8998"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/k8s
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: raju
    depends_on:
      - db
    networks:
      - springboot-mysql-net

volumes:
  db_data: # Persistent storage for the database

networks:
  springboot-mysql-net: # Custom network to connect services
---