version: "3"
services:
  server:
    image: docker-spring-image:latest
    ports:
      - "8008:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/employeedb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=1234
#    environment:
#      - spring.datasource.url=jdbc:mysql://mysqldb:3306/employeedb  #?useSSL=false
    networks:
      - springmysql-net

    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0.36
    ports:
      - 3307:3306
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=employeedb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234

networks:
  springmysql-net: