# sonarqube-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: sonarqube
  type: ClusterIP
---